on: push
name: Build Debug
jobs:
  build:
    name: Build APK
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.0'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi -vv
    - name: Create a Build APK
      uses: ncipollo/release-action@v1.6.1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: '1.0.0'
        commit: 'master'
        allowUpdates: true
